### ISSUE TITLE
Install as a Clojure CLI tool

### ISSUE THREAD

**Issue by pilosus** [scarletcomply/license-finder#5]
Hi there!

## Problem

Generating reports programmatically from the code may be too cumbersome: I need to add `license-finder` to my `deps.edn`, then add a few lines to a `build.clj` and then configure my CI or fire up my IDE with Clojure REPL to check the licenses.

Sometimes I may also want to generate a license report for someone else's Clojure library. Maybe because the authords don't use `license-finder` and I am not sure if their project's license is compliant with the dependencies they use.

## How I'd like to solve the problem?

I want to be able to generate a license report from the command line with no need to change files in the project I generate a report for.

Starting from Clojure CLI v1.11.1.1139 you can intall a library as a [tool](https://clojure.org/reference/deps_and_cli#tool_install).
Many Clojure tools use it already, e.g. [antq](https://github.com/liquidz/antq) for checking outdated deps, [clj-watson](https://github.com/clj-holmes/clj-watson) a vuln detection tool, [deps-new](https://github.com/seancorfield/deps-new) a tool for bootstrapping a Clojure app or a lib, and so forth.

We could do something similar:

```bash
# Install tool (latest version)
clojure -Ttools install-latest :lib com.github.scarletcomply/license-finder :as license-finder

# Install tool (certain version)
clojure -Ttools com.github.scarletcomply/license-finder '{:git/sha "..."}' :as license-finder

# Remove tool
clojure -Ttools remove :tool license-finder

# Update tool
clojure -Ttools install-latest :tool license-finder

# Generate report with sensible defaults
clojure -Tlicense-finder report

# Generate report for all deps including transitive ones
clojure -Tlicense-finder report :transitive? true
```

I've drafted a PR that covers the problem, please take a look.

**Comment by ferdinand-beyer** [comment]
Thanks for raising this! We will have a look at your PR soon!
